version: "3.8"

services:
  backend:
    build: ./backend
    container_name: spreadit_api
    restart: always
    env_file: .env
    ports:
      - "8000"
    networks:
      - spreadit_network

  frontend:
    build: ./frontend
    container_name: spreadit_frontend
    restart: always
    ports:
      - "80"
    depends_on:
      - backend
    networks:
      - spreadit_network

  nginx:
    image: nginx:latest
    container_name: spreadit_nginx_proxy
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - spreadit_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  spreadit_network:
    driver: bridge
