version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: news_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - news_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:
    name: news_redis_data

networks:
  news_network:
    name: news_network
    driver: bridge