# Generated by Django 5.1.5 on 2025-02-01 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="read",
            new_name="is_read",
        ),
    ]
