# Generated by Django 5.1.5 on 2025-02-02 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_rename_read_news_is_read"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="receivers",
            field=models.ManyToManyField(
                blank=True, related_name="received_news", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
