# Generated by Django 5.1.5 on 2025-02-02 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_receivers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="receivers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="received_news",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
