# Generated by Django 5.1.5 on 2025-02-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_news_receivers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-id"]},
        ),
    ]
